name: Test actions

on:
  push:

jobs:
  build-go:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Remove old build
        run: |
          rm -rf build
        working-directory: ./
      - name: Run go uild
        run: |
          go build --o ../build
        working-directory: src/